spring:
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: mindgate123
server:
  port: 8083
  servlet:
   context-path: /entity